
---

plugins:
  - babel
  - jest

# https://eslint.org/docs/user-guide/configuring#specifying-environments
env:
  node: true
  jest: true

parser: babel-eslint

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'
 

rules:
  no-console: 0
